# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.paginated_scan_list import PaginatedScanList  # noqa: E501
from swagger_client.rest import ApiException


class TestPaginatedScanList(unittest.TestCase):
    """PaginatedScanList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedScanList(self):
        """Test PaginatedScanList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.paginated_scan_list.PaginatedScanList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
