# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.type_d4d_enum import TypeD4dEnum  # noqa: E501
from swagger_client.rest import ApiException


class TestTypeD4dEnum(unittest.TestCase):
    """TypeD4dEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypeD4dEnum(self):
        """Test TypeD4dEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.type_d4d_enum.TypeD4dEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
