# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.integration_api import IntegrationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIntegrationApi(unittest.TestCase):
    """IntegrationApi unit test stubs"""

    def setUp(self):
        self.api = IntegrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_integrations_create(self):
        """Test case for integrations_create

        Create a new integration  # noqa: E501
        """
        pass

    def test_integrations_destroy(self):
        """Test case for integrations_destroy

        Delete an integration  # noqa: E501
        """
        pass

    def test_integrations_list(self):
        """Test case for integrations_list

        List all integrations  # noqa: E501
        """
        pass

    def test_integrations_partial_update(self):
        """Test case for integrations_partial_update

        Partially update an integration  # noqa: E501
        """
        pass

    def test_integrations_retrieve(self):
        """Test case for integrations_retrieve

        Retrieve integration details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
