# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.type34d_enum import Type34dEnum  # noqa: E501
from swagger_client.rest import ApiException


class TestType34dEnum(unittest.TestCase):
    """Type34dEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testType34dEnum(self):
        """Test Type34dEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.type34d_enum.Type34dEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
