# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.provider_api import ProviderApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProviderApi(unittest.TestCase):
    """ProviderApi unit test stubs"""

    def setUp(self):
        self.api = ProviderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_providers_connection_create(self):
        """Test case for providers_connection_create

        Check connection  # noqa: E501
        """
        pass

    def test_providers_create(self):
        """Test case for providers_create

        Create a new provider  # noqa: E501
        """
        pass

    def test_providers_destroy(self):
        """Test case for providers_destroy

        Delete a provider  # noqa: E501
        """
        pass

    def test_providers_list(self):
        """Test case for providers_list

        List all providers  # noqa: E501
        """
        pass

    def test_providers_partial_update(self):
        """Test case for providers_partial_update

        Partially update a provider  # noqa: E501
        """
        pass

    def test_providers_retrieve(self):
        """Test case for providers_retrieve

        Retrieve data from a provider  # noqa: E501
        """
        pass

    def test_providers_secrets_create(self):
        """Test case for providers_secrets_create

        Create a new secret  # noqa: E501
        """
        pass

    def test_providers_secrets_destroy(self):
        """Test case for providers_secrets_destroy

        Delete a secret  # noqa: E501
        """
        pass

    def test_providers_secrets_list(self):
        """Test case for providers_secrets_list

        List all secrets  # noqa: E501
        """
        pass

    def test_providers_secrets_partial_update(self):
        """Test case for providers_secrets_partial_update

        Partially update a secret  # noqa: E501
        """
        pass

    def test_providers_secrets_retrieve(self):
        """Test case for providers_secrets_retrieve

        Retrieve data from a secret  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
