# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.invitations_data import InvitationsData  # noqa: E501
from swagger_client.rest import ApiException


class TestInvitationsData(unittest.TestCase):
    """InvitationsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitationsData(self):
        """Test InvitationsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.invitations_data.InvitationsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
