# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.compliance_overview_full_attributes_requirements_requirement_id_checks_status import ComplianceOverviewFullAttributesRequirementsRequirementIdChecksStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestComplianceOverviewFullAttributesRequirementsRequirementIdChecksStatus(unittest.TestCase):
    """ComplianceOverviewFullAttributesRequirementsRequirementIdChecksStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplianceOverviewFullAttributesRequirementsRequirementIdChecksStatus(self):
        """Test ComplianceOverviewFullAttributesRequirementsRequirementIdChecksStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.compliance_overview_full_attributes_requirements_requirement_id_checks_status.ComplianceOverviewFullAttributesRequirementsRequirementIdChecksStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
