# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.invitation_api import InvitationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInvitationApi(unittest.TestCase):
    """InvitationApi unit test stubs"""

    def setUp(self):
        self.api = InvitationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_invitations_accept_create(self):
        """Test case for invitations_accept_create

        Accept an invitation  # noqa: E501
        """
        pass

    def test_tenants_invitations_create(self):
        """Test case for tenants_invitations_create

        Invite a user to a tenant  # noqa: E501
        """
        pass

    def test_tenants_invitations_destroy(self):
        """Test case for tenants_invitations_destroy

        Revoke a tenant invitation  # noqa: E501
        """
        pass

    def test_tenants_invitations_list(self):
        """Test case for tenants_invitations_list

        List all invitations  # noqa: E501
        """
        pass

    def test_tenants_invitations_partial_update(self):
        """Test case for tenants_invitations_partial_update

        Partially update a tenant invitation  # noqa: E501
        """
        pass

    def test_tenants_invitations_retrieve(self):
        """Test case for tenants_invitations_retrieve

        Retrieve data from a tenant invitation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
