# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.invitation_create_response import InvitationCreateResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestInvitationCreateResponse(unittest.TestCase):
    """InvitationCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitationCreateResponse(self):
        """Test InvitationCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.invitation_create_response.InvitationCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
