# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.compliance_overview_api import ComplianceOverviewApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComplianceOverviewApi(unittest.TestCase):
    """ComplianceOverviewApi unit test stubs"""

    def setUp(self):
        self.api = ComplianceOverviewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_compliance_overviews_list(self):
        """Test case for compliance_overviews_list

        List compliance overviews for a scan  # noqa: E501
        """
        pass

    def test_compliance_overviews_retrieve(self):
        """Test case for compliance_overviews_retrieve

        Retrieve data from a specific compliance overview  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
