# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.provider_group_create_request import ProviderGroupCreateRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestProviderGroupCreateRequest(unittest.TestCase):
    """ProviderGroupCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderGroupCreateRequest(self):
        """Test ProviderGroupCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.provider_group_create_request.ProviderGroupCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
