# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.provider_group_api import ProviderGroupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProviderGroupApi(unittest.TestCase):
    """ProviderGroupApi unit test stubs"""

    def setUp(self):
        self.api = ProviderGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_provider_groups_create(self):
        """Test case for provider_groups_create

        Create a new provider group  # noqa: E501
        """
        pass

    def test_provider_groups_destroy(self):
        """Test case for provider_groups_destroy

        Delete a provider group  # noqa: E501
        """
        pass

    def test_provider_groups_list(self):
        """Test case for provider_groups_list

        List all provider groups  # noqa: E501
        """
        pass

    def test_provider_groups_partial_update(self):
        """Test case for provider_groups_partial_update

        Partially update a provider group  # noqa: E501
        """
        pass

    def test_provider_groups_relationships_providers_create(self):
        """Test case for provider_groups_relationships_providers_create

        Create a new provider_group-providers relationship  # noqa: E501
        """
        pass

    def test_provider_groups_relationships_providers_destroy(self):
        """Test case for provider_groups_relationships_providers_destroy

        Delete a provider_group-providers relationship  # noqa: E501
        """
        pass

    def test_provider_groups_relationships_providers_partial_update(self):
        """Test case for provider_groups_relationships_providers_partial_update

        Partially update a provider_group-providers relationship  # noqa: E501
        """
        pass

    def test_provider_groups_retrieve(self):
        """Test case for provider_groups_retrieve

        Retrieve data from a provider group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
