# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.patched_provider_secret_update_request import PatchedProviderSecretUpdateRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestPatchedProviderSecretUpdateRequest(unittest.TestCase):
    """PatchedProviderSecretUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedProviderSecretUpdateRequest(self):
        """Test PatchedProviderSecretUpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.patched_provider_secret_update_request.PatchedProviderSecretUpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
