# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.finding_api import FindingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFindingApi(unittest.TestCase):
    """FindingApi unit test stubs"""

    def setUp(self):
        self.api = FindingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_findings_findings_services_regions_retrieve(self):
        """Test case for findings_findings_services_regions_retrieve

        Retrieve the services and regions that are impacted by findings  # noqa: E501
        """
        pass

    def test_findings_list(self):
        """Test case for findings_list

        List all findings  # noqa: E501
        """
        pass

    def test_findings_metadata_retrieve(self):
        """Test case for findings_metadata_retrieve

        Retrieve metadata values from findings  # noqa: E501
        """
        pass

    def test_findings_retrieve(self):
        """Test case for findings_retrieve

        Retrieve data from a specific finding  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
