# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_scan_update_type import AllOfScanUpdateType  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfScanUpdateType(unittest.TestCase):
    """AllOfScanUpdateType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfScanUpdateType(self):
        """Test AllOfScanUpdateType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_scan_update_type.AllOfScanUpdateType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
