# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.overview_provider_attributes_findings import OverviewProviderAttributesFindings  # noqa: E501
from swagger_client.rest import ApiException


class TestOverviewProviderAttributesFindings(unittest.TestCase):
    """OverviewProviderAttributesFindings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOverviewProviderAttributesFindings(self):
        """Test OverviewProviderAttributesFindings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.overview_provider_attributes_findings.OverviewProviderAttributesFindings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
