# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scan_api import ScanApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScanApi(unittest.TestCase):
    """ScanApi unit test stubs"""

    def setUp(self):
        self.api = ScanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_scans_create(self):
        """Test case for scans_create

        Trigger a manual scan  # noqa: E501
        """
        pass

    def test_scans_list(self):
        """Test case for scans_list

        List all scans  # noqa: E501
        """
        pass

    def test_scans_partial_update(self):
        """Test case for scans_partial_update

        Partially update a scan  # noqa: E501
        """
        pass

    def test_scans_report_retrieve(self):
        """Test case for scans_report_retrieve

        Download ZIP report  # noqa: E501
        """
        pass

    def test_scans_retrieve(self):
        """Test case for scans_retrieve

        Retrieve data from a specific scan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
