# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resource_identifier8 import ResourceIdentifier8  # noqa: E501
from swagger_client.rest import ApiException


class TestResourceIdentifier8(unittest.TestCase):
    """ResourceIdentifier8 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceIdentifier8(self):
        """Test ResourceIdentifier8"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resource_identifier8.ResourceIdentifier8()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
