# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_create(self):
        """Test case for users_create

        Register a new user  # noqa: E501
        """
        pass

    def test_users_destroy(self):
        """Test case for users_destroy

        Delete the user account  # noqa: E501
        """
        pass

    def test_users_list(self):
        """Test case for users_list

        List all users  # noqa: E501
        """
        pass

    def test_users_me_retrieve(self):
        """Test case for users_me_retrieve

        Retrieve the current user's information  # noqa: E501
        """
        pass

    def test_users_memberships_list(self):
        """Test case for users_memberships_list

        List user memberships  # noqa: E501
        """
        pass

    def test_users_memberships_retrieve(self):
        """Test case for users_memberships_retrieve

        Retrieve membership data from the user  # noqa: E501
        """
        pass

    def test_users_partial_update(self):
        """Test case for users_partial_update

        Update user information  # noqa: E501
        """
        pass

    def test_users_relationships_roles_create(self):
        """Test case for users_relationships_roles_create

        Create a new user-roles relationship  # noqa: E501
        """
        pass

    def test_users_relationships_roles_destroy(self):
        """Test case for users_relationships_roles_destroy

        Delete a user-roles relationship  # noqa: E501
        """
        pass

    def test_users_relationships_roles_partial_update(self):
        """Test case for users_relationships_roles_partial_update

        Partially update a user-roles relationship  # noqa: E501
        """
        pass

    def test_users_retrieve(self):
        """Test case for users_retrieve

        Retrieve a user's information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
