# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tenant_api import TenantApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTenantApi(unittest.TestCase):
    """TenantApi unit test stubs"""

    def setUp(self):
        self.api = TenantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_create(self):
        """Test case for tenants_create

        Create a new tenant  # noqa: E501
        """
        pass

    def test_tenants_destroy(self):
        """Test case for tenants_destroy

        Delete a tenant  # noqa: E501
        """
        pass

    def test_tenants_list(self):
        """Test case for tenants_list

        List all tenants  # noqa: E501
        """
        pass

    def test_tenants_memberships_destroy(self):
        """Test case for tenants_memberships_destroy

        Delete tenant memberships  # noqa: E501
        """
        pass

    def test_tenants_memberships_list(self):
        """Test case for tenants_memberships_list

        List tenant memberships  # noqa: E501
        """
        pass

    def test_tenants_partial_update(self):
        """Test case for tenants_partial_update

        Partially update a tenant  # noqa: E501
        """
        pass

    def test_tenants_retrieve(self):
        """Test case for tenants_retrieve

        Retrieve data from a tenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
