# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.overview_finding_attributes import OverviewFindingAttributes  # noqa: E501
from swagger_client.rest import ApiException


class TestOverviewFindingAttributes(unittest.TestCase):
    """OverviewFindingAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOverviewFindingAttributes(self):
        """Test OverviewFindingAttributes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.overview_finding_attributes.OverviewFindingAttributes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
