# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tenant_request_data import TenantRequestData  # noqa: E501
from swagger_client.rest import ApiException


class TestTenantRequestData(unittest.TestCase):
    """TenantRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTenantRequestData(self):
        """Test TenantRequestData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tenant_request_data.TenantRequestData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
