# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resource_identifier5_data import ResourceIdentifier5Data  # noqa: E501
from swagger_client.rest import ApiException


class TestResourceIdentifier5Data(unittest.TestCase):
    """ResourceIdentifier5Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceIdentifier5Data(self):
        """Test ResourceIdentifier5Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resource_identifier5_data.ResourceIdentifier5Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
