# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.task_api import TaskApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_destroy(self):
        """Test case for tasks_destroy

        Revoke a task  # noqa: E501
        """
        pass

    def test_tasks_list(self):
        """Test case for tasks_list

        List all tasks  # noqa: E501
        """
        pass

    def test_tasks_retrieve(self):
        """Test case for tasks_retrieve

        Retrieve data from a specific task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
