# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.patched_invitation_update_request_data import PatchedInvitationUpdateRequestData  # noqa: E501
from swagger_client.rest import ApiException


class TestPatchedInvitationUpdateRequestData(unittest.TestCase):
    """PatchedInvitationUpdateRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedInvitationUpdateRequestData(self):
        """Test PatchedInvitationUpdateRequestData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.patched_invitation_update_request_data.PatchedInvitationUpdateRequestData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
