# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.compliance_overview_full_attributes_requirements_requirement_id_checks_check_name import ComplianceOverviewFullAttributesRequirementsRequirementIdChecksCheckName  # noqa: E501
from swagger_client.rest import ApiException


class TestComplianceOverviewFullAttributesRequirementsRequirementIdChecksCheckName(unittest.TestCase):
    """ComplianceOverviewFullAttributesRequirementsRequirementIdChecksCheckName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplianceOverviewFullAttributesRequirementsRequirementIdChecksCheckName(self):
        """Test ComplianceOverviewFullAttributesRequirementsRequirementIdChecksCheckName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.compliance_overview_full_attributes_requirements_requirement_id_checks_check_name.ComplianceOverviewFullAttributesRequirementsRequirementIdChecksCheckName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
