# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_overview_finding_type import AllOfOverviewFindingType  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfOverviewFindingType(unittest.TestCase):
    """AllOfOverviewFindingType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfOverviewFindingType(self):
        """Test AllOfOverviewFindingType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_overview_finding_type.AllOfOverviewFindingType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
