# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.patched_provider_update_request import PatchedProviderUpdateRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestPatchedProviderUpdateRequest(unittest.TestCase):
    """PatchedProviderUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedProviderUpdateRequest(self):
        """Test PatchedProviderUpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.patched_provider_update_request.PatchedProviderUpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
