# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FindingMetadataAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'services': 'list[str]',
        'regions': 'list[str]',
        'resource_types': 'list[str]'
    }

    attribute_map = {
        'services': 'services',
        'regions': 'regions',
        'resource_types': 'resource_types'
    }

    def __init__(self, services=None, regions=None, resource_types=None):  # noqa: E501
        """FindingMetadataAttributes - a model defined in Swagger"""  # noqa: E501
        self._services = None
        self._regions = None
        self._resource_types = None
        self.discriminator = None
        self.services = services
        self.regions = regions
        self.resource_types = resource_types

    @property
    def services(self):
        """Gets the services of this FindingMetadataAttributes.  # noqa: E501


        :return: The services of this FindingMetadataAttributes.  # noqa: E501
        :rtype: list[str]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this FindingMetadataAttributes.


        :param services: The services of this FindingMetadataAttributes.  # noqa: E501
        :type: list[str]
        """
        if services is None:
            raise ValueError("Invalid value for `services`, must not be `None`")  # noqa: E501

        self._services = services

    @property
    def regions(self):
        """Gets the regions of this FindingMetadataAttributes.  # noqa: E501


        :return: The regions of this FindingMetadataAttributes.  # noqa: E501
        :rtype: list[str]
        """
        return self._regions

    @regions.setter
    def regions(self, regions):
        """Sets the regions of this FindingMetadataAttributes.


        :param regions: The regions of this FindingMetadataAttributes.  # noqa: E501
        :type: list[str]
        """
        if regions is None:
            raise ValueError("Invalid value for `regions`, must not be `None`")  # noqa: E501

        self._regions = regions

    @property
    def resource_types(self):
        """Gets the resource_types of this FindingMetadataAttributes.  # noqa: E501


        :return: The resource_types of this FindingMetadataAttributes.  # noqa: E501
        :rtype: list[str]
        """
        return self._resource_types

    @resource_types.setter
    def resource_types(self, resource_types):
        """Sets the resource_types of this FindingMetadataAttributes.


        :param resource_types: The resource_types of this FindingMetadataAttributes.  # noqa: E501
        :type: list[str]
        """
        if resource_types is None:
            raise ValueError("Invalid value for `resource_types`, must not be `None`")  # noqa: E501

        self._resource_types = resource_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FindingMetadataAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FindingMetadataAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
