# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OverviewSeverityAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'critical': 'int',
        'high': 'int',
        'medium': 'int',
        'low': 'int',
        'informational': 'int'
    }

    attribute_map = {
        'id': 'id',
        'critical': 'critical',
        'high': 'high',
        'medium': 'medium',
        'low': 'low',
        'informational': 'informational'
    }

    def __init__(self, id='n/a', critical=None, high=None, medium=None, low=None, informational=None):  # noqa: E501
        """OverviewSeverityAttributes - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._critical = None
        self._high = None
        self._medium = None
        self._low = None
        self._informational = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.critical = critical
        self.high = high
        self.medium = medium
        self.low = low
        self.informational = informational

    @property
    def id(self):
        """Gets the id of this OverviewSeverityAttributes.  # noqa: E501


        :return: The id of this OverviewSeverityAttributes.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OverviewSeverityAttributes.


        :param id: The id of this OverviewSeverityAttributes.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def critical(self):
        """Gets the critical of this OverviewSeverityAttributes.  # noqa: E501


        :return: The critical of this OverviewSeverityAttributes.  # noqa: E501
        :rtype: int
        """
        return self._critical

    @critical.setter
    def critical(self, critical):
        """Sets the critical of this OverviewSeverityAttributes.


        :param critical: The critical of this OverviewSeverityAttributes.  # noqa: E501
        :type: int
        """
        if critical is None:
            raise ValueError("Invalid value for `critical`, must not be `None`")  # noqa: E501

        self._critical = critical

    @property
    def high(self):
        """Gets the high of this OverviewSeverityAttributes.  # noqa: E501


        :return: The high of this OverviewSeverityAttributes.  # noqa: E501
        :rtype: int
        """
        return self._high

    @high.setter
    def high(self, high):
        """Sets the high of this OverviewSeverityAttributes.


        :param high: The high of this OverviewSeverityAttributes.  # noqa: E501
        :type: int
        """
        if high is None:
            raise ValueError("Invalid value for `high`, must not be `None`")  # noqa: E501

        self._high = high

    @property
    def medium(self):
        """Gets the medium of this OverviewSeverityAttributes.  # noqa: E501


        :return: The medium of this OverviewSeverityAttributes.  # noqa: E501
        :rtype: int
        """
        return self._medium

    @medium.setter
    def medium(self, medium):
        """Sets the medium of this OverviewSeverityAttributes.


        :param medium: The medium of this OverviewSeverityAttributes.  # noqa: E501
        :type: int
        """
        if medium is None:
            raise ValueError("Invalid value for `medium`, must not be `None`")  # noqa: E501

        self._medium = medium

    @property
    def low(self):
        """Gets the low of this OverviewSeverityAttributes.  # noqa: E501


        :return: The low of this OverviewSeverityAttributes.  # noqa: E501
        :rtype: int
        """
        return self._low

    @low.setter
    def low(self, low):
        """Sets the low of this OverviewSeverityAttributes.


        :param low: The low of this OverviewSeverityAttributes.  # noqa: E501
        :type: int
        """
        if low is None:
            raise ValueError("Invalid value for `low`, must not be `None`")  # noqa: E501

        self._low = low

    @property
    def informational(self):
        """Gets the informational of this OverviewSeverityAttributes.  # noqa: E501


        :return: The informational of this OverviewSeverityAttributes.  # noqa: E501
        :rtype: int
        """
        return self._informational

    @informational.setter
    def informational(self, informational):
        """Sets the informational of this OverviewSeverityAttributes.


        :param informational: The informational of this OverviewSeverityAttributes.  # noqa: E501
        :type: int
        """
        if informational is None:
            raise ValueError("Invalid value for `informational`, must not be `None`")  # noqa: E501

        self._informational = informational

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OverviewSeverityAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OverviewSeverityAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
