# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProviderSecretAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'inserted_at': 'datetime',
        'updated_at': 'datetime',
        'name': 'str',
        'secret_type': 'str'
    }

    attribute_map = {
        'inserted_at': 'inserted_at',
        'updated_at': 'updated_at',
        'name': 'name',
        'secret_type': 'secret_type'
    }

    def __init__(self, inserted_at=None, updated_at=None, name=None, secret_type=None):  # noqa: E501
        """ProviderSecretAttributes - a model defined in Swagger"""  # noqa: E501
        self._inserted_at = None
        self._updated_at = None
        self._name = None
        self._secret_type = None
        self.discriminator = None
        if inserted_at is not None:
            self.inserted_at = inserted_at
        if updated_at is not None:
            self.updated_at = updated_at
        if name is not None:
            self.name = name
        self.secret_type = secret_type

    @property
    def inserted_at(self):
        """Gets the inserted_at of this ProviderSecretAttributes.  # noqa: E501


        :return: The inserted_at of this ProviderSecretAttributes.  # noqa: E501
        :rtype: datetime
        """
        return self._inserted_at

    @inserted_at.setter
    def inserted_at(self, inserted_at):
        """Sets the inserted_at of this ProviderSecretAttributes.


        :param inserted_at: The inserted_at of this ProviderSecretAttributes.  # noqa: E501
        :type: datetime
        """

        self._inserted_at = inserted_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ProviderSecretAttributes.  # noqa: E501


        :return: The updated_at of this ProviderSecretAttributes.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ProviderSecretAttributes.


        :param updated_at: The updated_at of this ProviderSecretAttributes.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def name(self):
        """Gets the name of this ProviderSecretAttributes.  # noqa: E501


        :return: The name of this ProviderSecretAttributes.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProviderSecretAttributes.


        :param name: The name of this ProviderSecretAttributes.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def secret_type(self):
        """Gets the secret_type of this ProviderSecretAttributes.  # noqa: E501

        * `static` - Key-value pairs * `role` - Role assumption  # noqa: E501

        :return: The secret_type of this ProviderSecretAttributes.  # noqa: E501
        :rtype: str
        """
        return self._secret_type

    @secret_type.setter
    def secret_type(self, secret_type):
        """Sets the secret_type of this ProviderSecretAttributes.

        * `static` - Key-value pairs * `role` - Role assumption  # noqa: E501

        :param secret_type: The secret_type of this ProviderSecretAttributes.  # noqa: E501
        :type: str
        """
        if secret_type is None:
            raise ValueError("Invalid value for `secret_type`, must not be `None`")  # noqa: E501
        allowed_values = ["static", "role"]  # noqa: E501
        if secret_type not in allowed_values:
            raise ValueError(
                "Invalid value for `secret_type` ({0}), must be one of {1}"  # noqa: E501
                .format(secret_type, allowed_values)
            )

        self._secret_type = secret_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProviderSecretAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProviderSecretAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
