# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResourceAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'inserted_at': 'datetime',
        'updated_at': 'datetime',
        'uid': 'str',
        'name': 'str',
        'region': 'str',
        'service': 'str',
        'tags': 'object',
        'type': 'str'
    }

    attribute_map = {
        'inserted_at': 'inserted_at',
        'updated_at': 'updated_at',
        'uid': 'uid',
        'name': 'name',
        'region': 'region',
        'service': 'service',
        'tags': 'tags',
        'type': 'type'
    }

    def __init__(self, inserted_at=None, updated_at=None, uid=None, name=None, region=None, service=None, tags=None, type=None):  # noqa: E501
        """ResourceAttributes - a model defined in Swagger"""  # noqa: E501
        self._inserted_at = None
        self._updated_at = None
        self._uid = None
        self._name = None
        self._region = None
        self._service = None
        self._tags = None
        self._type = None
        self.discriminator = None
        if inserted_at is not None:
            self.inserted_at = inserted_at
        if updated_at is not None:
            self.updated_at = updated_at
        self.uid = uid
        self.name = name
        self.region = region
        self.service = service
        if tags is not None:
            self.tags = tags
        if type is not None:
            self.type = type

    @property
    def inserted_at(self):
        """Gets the inserted_at of this ResourceAttributes.  # noqa: E501


        :return: The inserted_at of this ResourceAttributes.  # noqa: E501
        :rtype: datetime
        """
        return self._inserted_at

    @inserted_at.setter
    def inserted_at(self, inserted_at):
        """Sets the inserted_at of this ResourceAttributes.


        :param inserted_at: The inserted_at of this ResourceAttributes.  # noqa: E501
        :type: datetime
        """

        self._inserted_at = inserted_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ResourceAttributes.  # noqa: E501


        :return: The updated_at of this ResourceAttributes.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ResourceAttributes.


        :param updated_at: The updated_at of this ResourceAttributes.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def uid(self):
        """Gets the uid of this ResourceAttributes.  # noqa: E501


        :return: The uid of this ResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this ResourceAttributes.


        :param uid: The uid of this ResourceAttributes.  # noqa: E501
        :type: str
        """
        if uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    @property
    def name(self):
        """Gets the name of this ResourceAttributes.  # noqa: E501


        :return: The name of this ResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ResourceAttributes.


        :param name: The name of this ResourceAttributes.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def region(self):
        """Gets the region of this ResourceAttributes.  # noqa: E501


        :return: The region of this ResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this ResourceAttributes.


        :param region: The region of this ResourceAttributes.  # noqa: E501
        :type: str
        """
        if region is None:
            raise ValueError("Invalid value for `region`, must not be `None`")  # noqa: E501

        self._region = region

    @property
    def service(self):
        """Gets the service of this ResourceAttributes.  # noqa: E501


        :return: The service of this ResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this ResourceAttributes.


        :param service: The service of this ResourceAttributes.  # noqa: E501
        :type: str
        """
        if service is None:
            raise ValueError("Invalid value for `service`, must not be `None`")  # noqa: E501

        self._service = service

    @property
    def tags(self):
        """Gets the tags of this ResourceAttributes.  # noqa: E501

        Tags associated with the resource  # noqa: E501

        :return: The tags of this ResourceAttributes.  # noqa: E501
        :rtype: object
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ResourceAttributes.

        Tags associated with the resource  # noqa: E501

        :param tags: The tags of this ResourceAttributes.  # noqa: E501
        :type: object
        """

        self._tags = tags

    @property
    def type(self):
        """Gets the type of this ResourceAttributes.  # noqa: E501


        :return: The type of this ResourceAttributes.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ResourceAttributes.


        :param type: The type of this ResourceAttributes.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResourceAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
