# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserCreateRequestDataAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'password': 'str',
        'email': 'str',
        'company_name': 'str'
    }

    attribute_map = {
        'name': 'name',
        'password': 'password',
        'email': 'email',
        'company_name': 'company_name'
    }

    def __init__(self, name=None, password=None, email=None, company_name=None):  # noqa: E501
        """UserCreateRequestDataAttributes - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._password = None
        self._email = None
        self._company_name = None
        self.discriminator = None
        self.name = name
        self.password = password
        self.email = email
        if company_name is not None:
            self.company_name = company_name

    @property
    def name(self):
        """Gets the name of this UserCreateRequestDataAttributes.  # noqa: E501


        :return: The name of this UserCreateRequestDataAttributes.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserCreateRequestDataAttributes.


        :param name: The name of this UserCreateRequestDataAttributes.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def password(self):
        """Gets the password of this UserCreateRequestDataAttributes.  # noqa: E501


        :return: The password of this UserCreateRequestDataAttributes.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UserCreateRequestDataAttributes.


        :param password: The password of this UserCreateRequestDataAttributes.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def email(self):
        """Gets the email of this UserCreateRequestDataAttributes.  # noqa: E501

        Case insensitive  # noqa: E501

        :return: The email of this UserCreateRequestDataAttributes.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserCreateRequestDataAttributes.

        Case insensitive  # noqa: E501

        :param email: The email of this UserCreateRequestDataAttributes.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def company_name(self):
        """Gets the company_name of this UserCreateRequestDataAttributes.  # noqa: E501


        :return: The company_name of this UserCreateRequestDataAttributes.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this UserCreateRequestDataAttributes.


        :param company_name: The company_name of this UserCreateRequestDataAttributes.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserCreateRequestDataAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserCreateRequestDataAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
