# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ComplianceOverviewApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def compliance_overviews_list(self, filter_scan_id, **kwargs):  # noqa: E501
        """List compliance overviews for a scan  # noqa: E501

        Retrieve an overview of all the compliance in a given scan. If no region filters are provided, the region with the most fails will be returned by default.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.compliance_overviews_list(filter_scan_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filter_scan_id: Related scan ID. (required)
        :param list[str] fields_compliance_overviews: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param str filter_compliance_id:
        :param str filter_compliance_id__icontains:
        :param str filter_framework:
        :param str filter_framework__icontains:
        :param str filter_framework__iexact:
        :param date filter_inserted_at:
        :param date filter_inserted_at__date:
        :param datetime filter_inserted_at__gte:
        :param datetime filter_inserted_at__lte:
        :param str filter_provider_type: * `aws` - AWS * `azure` - Azure * `gcp` - GCP * `kubernetes` - Kubernetes
        :param list[str] filter_provider_type__in: Multiple values may be separated by commas.  * `aws` - AWS * `azure` - Azure * `gcp` - GCP * `kubernetes` - Kubernetes
        :param str filter_region:
        :param str filter_region__icontains:
        :param list[str] filter_region__in: Multiple values may be separated by commas.
        :param str filter_search: A search term.
        :param str filter_version:
        :param str filter_version__icontains:
        :param int page_number: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param list[str] sort: [list of fields to sort by](https://jsonapi.org/format/#fetching-sorting)
        :return: PaginatedComplianceOverviewList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.compliance_overviews_list_with_http_info(filter_scan_id, **kwargs)  # noqa: E501
        else:
            (data) = self.compliance_overviews_list_with_http_info(filter_scan_id, **kwargs)  # noqa: E501
            return data

    def compliance_overviews_list_with_http_info(self, filter_scan_id, **kwargs):  # noqa: E501
        """List compliance overviews for a scan  # noqa: E501

        Retrieve an overview of all the compliance in a given scan. If no region filters are provided, the region with the most fails will be returned by default.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.compliance_overviews_list_with_http_info(filter_scan_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filter_scan_id: Related scan ID. (required)
        :param list[str] fields_compliance_overviews: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param str filter_compliance_id:
        :param str filter_compliance_id__icontains:
        :param str filter_framework:
        :param str filter_framework__icontains:
        :param str filter_framework__iexact:
        :param date filter_inserted_at:
        :param date filter_inserted_at__date:
        :param datetime filter_inserted_at__gte:
        :param datetime filter_inserted_at__lte:
        :param str filter_provider_type: * `aws` - AWS * `azure` - Azure * `gcp` - GCP * `kubernetes` - Kubernetes
        :param list[str] filter_provider_type__in: Multiple values may be separated by commas.  * `aws` - AWS * `azure` - Azure * `gcp` - GCP * `kubernetes` - Kubernetes
        :param str filter_region:
        :param str filter_region__icontains:
        :param list[str] filter_region__in: Multiple values may be separated by commas.
        :param str filter_search: A search term.
        :param str filter_version:
        :param str filter_version__icontains:
        :param int page_number: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param list[str] sort: [list of fields to sort by](https://jsonapi.org/format/#fetching-sorting)
        :return: PaginatedComplianceOverviewList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter_scan_id', 'fields_compliance_overviews', 'filter_compliance_id', 'filter_compliance_id__icontains', 'filter_framework', 'filter_framework__icontains', 'filter_framework__iexact', 'filter_inserted_at', 'filter_inserted_at__date', 'filter_inserted_at__gte', 'filter_inserted_at__lte', 'filter_provider_type', 'filter_provider_type__in', 'filter_region', 'filter_region__icontains', 'filter_region__in', 'filter_search', 'filter_version', 'filter_version__icontains', 'page_number', 'page_size', 'sort']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method compliance_overviews_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'filter_scan_id' is set
        if ('filter_scan_id' not in params or
                params['filter_scan_id'] is None):
            raise ValueError("Missing the required parameter `filter_scan_id` when calling `compliance_overviews_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'fields_compliance_overviews' in params:
            query_params.append(('fields[compliance-overviews]', params['fields_compliance_overviews']))  # noqa: E501
            collection_formats['fields[compliance-overviews]'] = 'csv'  # noqa: E501
        if 'filter_compliance_id' in params:
            query_params.append(('filter[compliance_id]', params['filter_compliance_id']))  # noqa: E501
        if 'filter_compliance_id__icontains' in params:
            query_params.append(('filter[compliance_id__icontains]', params['filter_compliance_id__icontains']))  # noqa: E501
        if 'filter_framework' in params:
            query_params.append(('filter[framework]', params['filter_framework']))  # noqa: E501
        if 'filter_framework__icontains' in params:
            query_params.append(('filter[framework__icontains]', params['filter_framework__icontains']))  # noqa: E501
        if 'filter_framework__iexact' in params:
            query_params.append(('filter[framework__iexact]', params['filter_framework__iexact']))  # noqa: E501
        if 'filter_inserted_at' in params:
            query_params.append(('filter[inserted_at]', params['filter_inserted_at']))  # noqa: E501
        if 'filter_inserted_at__date' in params:
            query_params.append(('filter[inserted_at__date]', params['filter_inserted_at__date']))  # noqa: E501
        if 'filter_inserted_at__gte' in params:
            query_params.append(('filter[inserted_at__gte]', params['filter_inserted_at__gte']))  # noqa: E501
        if 'filter_inserted_at__lte' in params:
            query_params.append(('filter[inserted_at__lte]', params['filter_inserted_at__lte']))  # noqa: E501
        if 'filter_provider_type' in params:
            query_params.append(('filter[provider_type]', params['filter_provider_type']))  # noqa: E501
        if 'filter_provider_type__in' in params:
            query_params.append(('filter[provider_type__in]', params['filter_provider_type__in']))  # noqa: E501
            collection_formats['filter[provider_type__in]'] = 'csv'  # noqa: E501
        if 'filter_region' in params:
            query_params.append(('filter[region]', params['filter_region']))  # noqa: E501
        if 'filter_region__icontains' in params:
            query_params.append(('filter[region__icontains]', params['filter_region__icontains']))  # noqa: E501
        if 'filter_region__in' in params:
            query_params.append(('filter[region__in]', params['filter_region__in']))  # noqa: E501
            collection_formats['filter[region__in]'] = 'csv'  # noqa: E501
        if 'filter_scan_id' in params:
            query_params.append(('filter[scan_id]', params['filter_scan_id']))  # noqa: E501
        if 'filter_search' in params:
            query_params.append(('filter[search]', params['filter_search']))  # noqa: E501
        if 'filter_version' in params:
            query_params.append(('filter[version]', params['filter_version']))  # noqa: E501
        if 'filter_version__icontains' in params:
            query_params.append(('filter[version__icontains]', params['filter_version__icontains']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501
            collection_formats['sort'] = 'csv'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/compliance-overviews', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedComplianceOverviewList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def compliance_overviews_retrieve(self, id, **kwargs):  # noqa: E501
        """Retrieve data from a specific compliance overview  # noqa: E501

        Fetch detailed information about a specific compliance overview by its ID, including detailed requirement information and check's status.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.compliance_overviews_retrieve(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this compliance overview. (required)
        :param list[str] fields_compliance_overviews: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :return: ComplianceOverviewFullResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.compliance_overviews_retrieve_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.compliance_overviews_retrieve_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def compliance_overviews_retrieve_with_http_info(self, id, **kwargs):  # noqa: E501
        """Retrieve data from a specific compliance overview  # noqa: E501

        Fetch detailed information about a specific compliance overview by its ID, including detailed requirement information and check's status.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.compliance_overviews_retrieve_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this compliance overview. (required)
        :param list[str] fields_compliance_overviews: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :return: ComplianceOverviewFullResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'fields_compliance_overviews']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method compliance_overviews_retrieve" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `compliance_overviews_retrieve`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'fields_compliance_overviews' in params:
            query_params.append(('fields[compliance-overviews]', params['fields_compliance_overviews']))  # noqa: E501
            collection_formats['fields[compliance-overviews]'] = 'csv'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/compliance-overviews/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ComplianceOverviewFullResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
