# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class IntegrationApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def integrations_create(self, body, **kwargs):  # noqa: E501
        """Create a new integration  # noqa: E501

        Register a new integration with the system, providing necessary configuration details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_create(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param IntegrationCreateRequest body: (required)
        :return: IntegrationCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_create_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.integrations_create_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def integrations_create_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create a new integration  # noqa: E501

        Register a new integration with the system, providing necessary configuration details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_create_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param IntegrationCreateRequest body: (required)
        :return: IntegrationCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `integrations_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IntegrationCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def integrations_create(self, data2, data, **kwargs):  # noqa: E501
        """Create a new integration  # noqa: E501

        Register a new integration with the system, providing necessary configuration details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_create(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param IntegrationCreateRequestData data2: (required)
        :param IntegrationCreateRequestData data: (required)
        :return: IntegrationCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_create_with_http_info(data2, data, **kwargs)  # noqa: E501
        else:
            (data) = self.integrations_create_with_http_info(data2, data, **kwargs)  # noqa: E501
            return data

    def integrations_create_with_http_info(self, data2, data, **kwargs):  # noqa: E501
        """Create a new integration  # noqa: E501

        Register a new integration with the system, providing necessary configuration details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_create_with_http_info(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param IntegrationCreateRequestData data2: (required)
        :param IntegrationCreateRequestData data: (required)
        :return: IntegrationCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `integrations_create`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `integrations_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IntegrationCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def integrations_create(self, data2, data, **kwargs):  # noqa: E501
        """Create a new integration  # noqa: E501

        Register a new integration with the system, providing necessary configuration details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_create(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param IntegrationCreateRequestData data2: (required)
        :param IntegrationCreateRequestData data: (required)
        :return: IntegrationCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_create_with_http_info(data2, data, **kwargs)  # noqa: E501
        else:
            (data) = self.integrations_create_with_http_info(data2, data, **kwargs)  # noqa: E501
            return data

    def integrations_create_with_http_info(self, data2, data, **kwargs):  # noqa: E501
        """Create a new integration  # noqa: E501

        Register a new integration with the system, providing necessary configuration details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_create_with_http_info(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param IntegrationCreateRequestData data2: (required)
        :param IntegrationCreateRequestData data: (required)
        :return: IntegrationCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `integrations_create`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `integrations_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IntegrationCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def integrations_destroy(self, id, **kwargs):  # noqa: E501
        """Delete an integration  # noqa: E501

        Remove an integration from the system by its ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_destroy(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this integration. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_destroy_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.integrations_destroy_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def integrations_destroy_with_http_info(self, id, **kwargs):  # noqa: E501
        """Delete an integration  # noqa: E501

        Remove an integration from the system by its ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_destroy_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this integration. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_destroy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `integrations_destroy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def integrations_list(self, **kwargs):  # noqa: E501
        """List all integrations  # noqa: E501

        Retrieve a list of all configured integrations with options for filtering by various criteria.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] fields_integrations: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param date filter_inserted_at:
        :param date filter_inserted_at__date:
        :param datetime filter_inserted_at__gte:
        :param datetime filter_inserted_at__lte:
        :param str filter_integration_type: * `amazon_s3` - Amazon S3 * `saml` - SAML * `aws_security_hub` - AWS Security Hub * `jira` - JIRA * `slack` - Slack
        :param list[str] filter_integration_type__in: Multiple values may be separated by commas.  * `amazon_s3` - Amazon S3 * `saml` - SAML * `aws_security_hub` - AWS Security Hub * `jira` - JIRA * `slack` - Slack
        :param str filter_search: A search term.
        :param list[str] include: include query parameter to allow the client to customize which related resources should be returned.
        :param int page_number: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param list[str] sort: [list of fields to sort by](https://jsonapi.org/format/#fetching-sorting)
        :return: PaginatedIntegrationList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.integrations_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def integrations_list_with_http_info(self, **kwargs):  # noqa: E501
        """List all integrations  # noqa: E501

        Retrieve a list of all configured integrations with options for filtering by various criteria.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] fields_integrations: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param date filter_inserted_at:
        :param date filter_inserted_at__date:
        :param datetime filter_inserted_at__gte:
        :param datetime filter_inserted_at__lte:
        :param str filter_integration_type: * `amazon_s3` - Amazon S3 * `saml` - SAML * `aws_security_hub` - AWS Security Hub * `jira` - JIRA * `slack` - Slack
        :param list[str] filter_integration_type__in: Multiple values may be separated by commas.  * `amazon_s3` - Amazon S3 * `saml` - SAML * `aws_security_hub` - AWS Security Hub * `jira` - JIRA * `slack` - Slack
        :param str filter_search: A search term.
        :param list[str] include: include query parameter to allow the client to customize which related resources should be returned.
        :param int page_number: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param list[str] sort: [list of fields to sort by](https://jsonapi.org/format/#fetching-sorting)
        :return: PaginatedIntegrationList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fields_integrations', 'filter_inserted_at', 'filter_inserted_at__date', 'filter_inserted_at__gte', 'filter_inserted_at__lte', 'filter_integration_type', 'filter_integration_type__in', 'filter_search', 'include', 'page_number', 'page_size', 'sort']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'fields_integrations' in params:
            query_params.append(('fields[integrations]', params['fields_integrations']))  # noqa: E501
            collection_formats['fields[integrations]'] = 'csv'  # noqa: E501
        if 'filter_inserted_at' in params:
            query_params.append(('filter[inserted_at]', params['filter_inserted_at']))  # noqa: E501
        if 'filter_inserted_at__date' in params:
            query_params.append(('filter[inserted_at__date]', params['filter_inserted_at__date']))  # noqa: E501
        if 'filter_inserted_at__gte' in params:
            query_params.append(('filter[inserted_at__gte]', params['filter_inserted_at__gte']))  # noqa: E501
        if 'filter_inserted_at__lte' in params:
            query_params.append(('filter[inserted_at__lte]', params['filter_inserted_at__lte']))  # noqa: E501
        if 'filter_integration_type' in params:
            query_params.append(('filter[integration_type]', params['filter_integration_type']))  # noqa: E501
        if 'filter_integration_type__in' in params:
            query_params.append(('filter[integration_type__in]', params['filter_integration_type__in']))  # noqa: E501
            collection_formats['filter[integration_type__in]'] = 'csv'  # noqa: E501
        if 'filter_search' in params:
            query_params.append(('filter[search]', params['filter_search']))  # noqa: E501
        if 'include' in params:
            query_params.append(('include', params['include']))  # noqa: E501
            collection_formats['include'] = 'csv'  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501
            collection_formats['sort'] = 'csv'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedIntegrationList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def integrations_partial_update(self, body, id, **kwargs):  # noqa: E501
        """Partially update an integration  # noqa: E501

        Modify certain fields of an existing integration without affecting other settings.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_partial_update(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedIntegrationUpdateRequest body: (required)
        :param str id: A UUID string identifying this integration. (required)
        :return: IntegrationUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_partial_update_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.integrations_partial_update_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def integrations_partial_update_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """Partially update an integration  # noqa: E501

        Modify certain fields of an existing integration without affecting other settings.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_partial_update_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedIntegrationUpdateRequest body: (required)
        :param str id: A UUID string identifying this integration. (required)
        :return: IntegrationUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `integrations_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `integrations_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IntegrationUpdateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def integrations_partial_update(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update an integration  # noqa: E501

        Modify certain fields of an existing integration without affecting other settings.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_partial_update(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedIntegrationUpdateRequestData data2: (required)
        :param PatchedIntegrationUpdateRequestData data: (required)
        :param str id: A UUID string identifying this integration. (required)
        :return: IntegrationUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
        else:
            (data) = self.integrations_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
            return data

    def integrations_partial_update_with_http_info(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update an integration  # noqa: E501

        Modify certain fields of an existing integration without affecting other settings.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_partial_update_with_http_info(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedIntegrationUpdateRequestData data2: (required)
        :param PatchedIntegrationUpdateRequestData data: (required)
        :param str id: A UUID string identifying this integration. (required)
        :return: IntegrationUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `integrations_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `integrations_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `integrations_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IntegrationUpdateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def integrations_partial_update(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update an integration  # noqa: E501

        Modify certain fields of an existing integration without affecting other settings.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_partial_update(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedIntegrationUpdateRequestData data2: (required)
        :param PatchedIntegrationUpdateRequestData data: (required)
        :param str id: A UUID string identifying this integration. (required)
        :return: IntegrationUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
        else:
            (data) = self.integrations_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
            return data

    def integrations_partial_update_with_http_info(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update an integration  # noqa: E501

        Modify certain fields of an existing integration without affecting other settings.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_partial_update_with_http_info(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedIntegrationUpdateRequestData data2: (required)
        :param PatchedIntegrationUpdateRequestData data: (required)
        :param str id: A UUID string identifying this integration. (required)
        :return: IntegrationUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `integrations_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `integrations_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `integrations_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IntegrationUpdateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def integrations_retrieve(self, id, **kwargs):  # noqa: E501
        """Retrieve integration details  # noqa: E501

        Fetch detailed information about a specific integration by its ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_retrieve(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this integration. (required)
        :param list[str] fields_integrations: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param list[str] include: include query parameter to allow the client to customize which related resources should be returned.
        :return: IntegrationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.integrations_retrieve_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.integrations_retrieve_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def integrations_retrieve_with_http_info(self, id, **kwargs):  # noqa: E501
        """Retrieve integration details  # noqa: E501

        Fetch detailed information about a specific integration by its ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.integrations_retrieve_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this integration. (required)
        :param list[str] fields_integrations: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param list[str] include: include query parameter to allow the client to customize which related resources should be returned.
        :return: IntegrationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'fields_integrations', 'include']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method integrations_retrieve" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `integrations_retrieve`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'fields_integrations' in params:
            query_params.append(('fields[integrations]', params['fields_integrations']))  # noqa: E501
            collection_formats['fields[integrations]'] = 'csv'  # noqa: E501
        if 'include' in params:
            query_params.append(('include', params['include']))  # noqa: E501
            collection_formats['include'] = 'csv'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/integrations/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IntegrationResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
