# coding: utf-8

"""
    Prowler API

    Prowler API specification.  This file is auto-generated.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ProviderApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def providers_connection_create(self, id, **kwargs):  # noqa: E501
        """Check connection  # noqa: E501

        Try to verify connection. For instance, Role & Credentials are set correctly  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_connection_create(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this provider. (required)
        :return: OpenApiResponseResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_connection_create_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_connection_create_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def providers_connection_create_with_http_info(self, id, **kwargs):  # noqa: E501
        """Check connection  # noqa: E501

        Try to verify connection. For instance, Role & Credentials are set correctly  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_connection_create_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this provider. (required)
        :return: OpenApiResponseResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_connection_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_connection_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/{id}/connection', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='OpenApiResponseResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_create(self, body, **kwargs):  # noqa: E501
        """Create a new provider  # noqa: E501

        Add a new provider to the system by providing the required provider details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_create(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderCreateRequest body: (required)
        :return: ProviderCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_create_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_create_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def providers_create_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create a new provider  # noqa: E501

        Add a new provider to the system by providing the required provider details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_create_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderCreateRequest body: (required)
        :return: ProviderCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `providers_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_create(self, data2, data, **kwargs):  # noqa: E501
        """Create a new provider  # noqa: E501

        Add a new provider to the system by providing the required provider details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_create(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderCreateRequestData data2: (required)
        :param ProviderCreateRequestData data: (required)
        :return: ProviderCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_create_with_http_info(data2, data, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_create_with_http_info(data2, data, **kwargs)  # noqa: E501
            return data

    def providers_create_with_http_info(self, data2, data, **kwargs):  # noqa: E501
        """Create a new provider  # noqa: E501

        Add a new provider to the system by providing the required provider details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_create_with_http_info(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderCreateRequestData data2: (required)
        :param ProviderCreateRequestData data: (required)
        :return: ProviderCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `providers_create`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `providers_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_create(self, data2, data, **kwargs):  # noqa: E501
        """Create a new provider  # noqa: E501

        Add a new provider to the system by providing the required provider details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_create(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderCreateRequestData data2: (required)
        :param ProviderCreateRequestData data: (required)
        :return: ProviderCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_create_with_http_info(data2, data, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_create_with_http_info(data2, data, **kwargs)  # noqa: E501
            return data

    def providers_create_with_http_info(self, data2, data, **kwargs):  # noqa: E501
        """Create a new provider  # noqa: E501

        Add a new provider to the system by providing the required provider details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_create_with_http_info(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderCreateRequestData data2: (required)
        :param ProviderCreateRequestData data: (required)
        :return: ProviderCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `providers_create`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `providers_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_destroy(self, id, **kwargs):  # noqa: E501
        """Delete a provider  # noqa: E501

        Remove a provider from the system by their ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_destroy(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this provider. (required)
        :return: OpenApiResponseResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_destroy_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_destroy_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def providers_destroy_with_http_info(self, id, **kwargs):  # noqa: E501
        """Delete a provider  # noqa: E501

        Remove a provider from the system by their ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_destroy_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this provider. (required)
        :return: OpenApiResponseResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_destroy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_destroy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='OpenApiResponseResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_list(self, **kwargs):  # noqa: E501
        """List all providers  # noqa: E501

        Retrieve a list of all providers with options for filtering by various criteria.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] fields_providers: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param str filter_alias:
        :param str filter_alias__icontains:
        :param list[str] filter_alias__in: Multiple values may be separated by commas.
        :param bool filter_connected:
        :param str filter_id:
        :param list[str] filter_id__in: Multiple values may be separated by commas.
        :param date filter_inserted_at:
        :param datetime filter_inserted_at__gte:
        :param datetime filter_inserted_at__lte:
        :param str filter_provider: * `aws` - AWS * `azure` - Azure * `gcp` - GCP * `kubernetes` - Kubernetes
        :param list[str] filter_provider__in: Multiple values may be separated by commas.
        :param str filter_search: A search term.
        :param str filter_uid:
        :param str filter_uid__icontains:
        :param list[str] filter_uid__in: Multiple values may be separated by commas.
        :param date filter_updated_at:
        :param datetime filter_updated_at__gte:
        :param datetime filter_updated_at__lte:
        :param list[str] include: include query parameter to allow the client to customize which related resources should be returned.
        :param int page_number: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param list[str] sort: [list of fields to sort by](https://jsonapi.org/format/#fetching-sorting)
        :return: PaginatedProviderList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.providers_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def providers_list_with_http_info(self, **kwargs):  # noqa: E501
        """List all providers  # noqa: E501

        Retrieve a list of all providers with options for filtering by various criteria.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] fields_providers: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param str filter_alias:
        :param str filter_alias__icontains:
        :param list[str] filter_alias__in: Multiple values may be separated by commas.
        :param bool filter_connected:
        :param str filter_id:
        :param list[str] filter_id__in: Multiple values may be separated by commas.
        :param date filter_inserted_at:
        :param datetime filter_inserted_at__gte:
        :param datetime filter_inserted_at__lte:
        :param str filter_provider: * `aws` - AWS * `azure` - Azure * `gcp` - GCP * `kubernetes` - Kubernetes
        :param list[str] filter_provider__in: Multiple values may be separated by commas.
        :param str filter_search: A search term.
        :param str filter_uid:
        :param str filter_uid__icontains:
        :param list[str] filter_uid__in: Multiple values may be separated by commas.
        :param date filter_updated_at:
        :param datetime filter_updated_at__gte:
        :param datetime filter_updated_at__lte:
        :param list[str] include: include query parameter to allow the client to customize which related resources should be returned.
        :param int page_number: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param list[str] sort: [list of fields to sort by](https://jsonapi.org/format/#fetching-sorting)
        :return: PaginatedProviderList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fields_providers', 'filter_alias', 'filter_alias__icontains', 'filter_alias__in', 'filter_connected', 'filter_id', 'filter_id__in', 'filter_inserted_at', 'filter_inserted_at__gte', 'filter_inserted_at__lte', 'filter_provider', 'filter_provider__in', 'filter_search', 'filter_uid', 'filter_uid__icontains', 'filter_uid__in', 'filter_updated_at', 'filter_updated_at__gte', 'filter_updated_at__lte', 'include', 'page_number', 'page_size', 'sort']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'fields_providers' in params:
            query_params.append(('fields[providers]', params['fields_providers']))  # noqa: E501
            collection_formats['fields[providers]'] = 'csv'  # noqa: E501
        if 'filter_alias' in params:
            query_params.append(('filter[alias]', params['filter_alias']))  # noqa: E501
        if 'filter_alias__icontains' in params:
            query_params.append(('filter[alias__icontains]', params['filter_alias__icontains']))  # noqa: E501
        if 'filter_alias__in' in params:
            query_params.append(('filter[alias__in]', params['filter_alias__in']))  # noqa: E501
            collection_formats['filter[alias__in]'] = 'csv'  # noqa: E501
        if 'filter_connected' in params:
            query_params.append(('filter[connected]', params['filter_connected']))  # noqa: E501
        if 'filter_id' in params:
            query_params.append(('filter[id]', params['filter_id']))  # noqa: E501
        if 'filter_id__in' in params:
            query_params.append(('filter[id__in]', params['filter_id__in']))  # noqa: E501
            collection_formats['filter[id__in]'] = 'csv'  # noqa: E501
        if 'filter_inserted_at' in params:
            query_params.append(('filter[inserted_at]', params['filter_inserted_at']))  # noqa: E501
        if 'filter_inserted_at__gte' in params:
            query_params.append(('filter[inserted_at__gte]', params['filter_inserted_at__gte']))  # noqa: E501
        if 'filter_inserted_at__lte' in params:
            query_params.append(('filter[inserted_at__lte]', params['filter_inserted_at__lte']))  # noqa: E501
        if 'filter_provider' in params:
            query_params.append(('filter[provider]', params['filter_provider']))  # noqa: E501
        if 'filter_provider__in' in params:
            query_params.append(('filter[provider__in]', params['filter_provider__in']))  # noqa: E501
            collection_formats['filter[provider__in]'] = 'csv'  # noqa: E501
        if 'filter_search' in params:
            query_params.append(('filter[search]', params['filter_search']))  # noqa: E501
        if 'filter_uid' in params:
            query_params.append(('filter[uid]', params['filter_uid']))  # noqa: E501
        if 'filter_uid__icontains' in params:
            query_params.append(('filter[uid__icontains]', params['filter_uid__icontains']))  # noqa: E501
        if 'filter_uid__in' in params:
            query_params.append(('filter[uid__in]', params['filter_uid__in']))  # noqa: E501
            collection_formats['filter[uid__in]'] = 'csv'  # noqa: E501
        if 'filter_updated_at' in params:
            query_params.append(('filter[updated_at]', params['filter_updated_at']))  # noqa: E501
        if 'filter_updated_at__gte' in params:
            query_params.append(('filter[updated_at__gte]', params['filter_updated_at__gte']))  # noqa: E501
        if 'filter_updated_at__lte' in params:
            query_params.append(('filter[updated_at__lte]', params['filter_updated_at__lte']))  # noqa: E501
        if 'include' in params:
            query_params.append(('include', params['include']))  # noqa: E501
            collection_formats['include'] = 'csv'  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501
            collection_formats['sort'] = 'csv'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedProviderList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_partial_update(self, body, id, **kwargs):  # noqa: E501
        """Partially update a provider  # noqa: E501

        Update certain fields of an existing provider's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_partial_update(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderUpdateRequest body: (required)
        :param str id: A UUID string identifying this provider. (required)
        :return: SerializerMetaclassResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_partial_update_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_partial_update_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def providers_partial_update_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """Partially update a provider  # noqa: E501

        Update certain fields of an existing provider's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_partial_update_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderUpdateRequest body: (required)
        :param str id: A UUID string identifying this provider. (required)
        :return: SerializerMetaclassResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `providers_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SerializerMetaclassResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_partial_update(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update a provider  # noqa: E501

        Update certain fields of an existing provider's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_partial_update(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderUpdateRequestData data2: (required)
        :param PatchedProviderUpdateRequestData data: (required)
        :param str id: A UUID string identifying this provider. (required)
        :return: SerializerMetaclassResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
            return data

    def providers_partial_update_with_http_info(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update a provider  # noqa: E501

        Update certain fields of an existing provider's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_partial_update_with_http_info(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderUpdateRequestData data2: (required)
        :param PatchedProviderUpdateRequestData data: (required)
        :param str id: A UUID string identifying this provider. (required)
        :return: SerializerMetaclassResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `providers_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `providers_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SerializerMetaclassResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_partial_update(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update a provider  # noqa: E501

        Update certain fields of an existing provider's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_partial_update(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderUpdateRequestData data2: (required)
        :param PatchedProviderUpdateRequestData data: (required)
        :param str id: A UUID string identifying this provider. (required)
        :return: SerializerMetaclassResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
            return data

    def providers_partial_update_with_http_info(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update a provider  # noqa: E501

        Update certain fields of an existing provider's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_partial_update_with_http_info(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderUpdateRequestData data2: (required)
        :param PatchedProviderUpdateRequestData data: (required)
        :param str id: A UUID string identifying this provider. (required)
        :return: SerializerMetaclassResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `providers_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `providers_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SerializerMetaclassResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_retrieve(self, id, **kwargs):  # noqa: E501
        """Retrieve data from a provider  # noqa: E501

        Fetch detailed information about a specific provider by their ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_retrieve(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this provider. (required)
        :param list[str] fields_providers: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param list[str] include: include query parameter to allow the client to customize which related resources should be returned.
        :return: ProviderResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_retrieve_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_retrieve_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def providers_retrieve_with_http_info(self, id, **kwargs):  # noqa: E501
        """Retrieve data from a provider  # noqa: E501

        Fetch detailed information about a specific provider by their ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_retrieve_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: A UUID string identifying this provider. (required)
        :param list[str] fields_providers: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param list[str] include: include query parameter to allow the client to customize which related resources should be returned.
        :return: ProviderResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'fields_providers', 'include']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_retrieve" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_retrieve`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'fields_providers' in params:
            query_params.append(('fields[providers]', params['fields_providers']))  # noqa: E501
            collection_formats['fields[providers]'] = 'csv'  # noqa: E501
        if 'include' in params:
            query_params.append(('include', params['include']))  # noqa: E501
            collection_formats['include'] = 'csv'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_create(self, body, **kwargs):  # noqa: E501
        """Create a new secret  # noqa: E501

        Add a new secret to the system by providing the required secret details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_create(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderSecretCreateRequest body: (required)
        :return: ProviderSecretCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_create_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_create_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def providers_secrets_create_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create a new secret  # noqa: E501

        Add a new secret to the system by providing the required secret details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_create_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderSecretCreateRequest body: (required)
        :return: ProviderSecretCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `providers_secrets_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderSecretCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_create(self, data2, data, **kwargs):  # noqa: E501
        """Create a new secret  # noqa: E501

        Add a new secret to the system by providing the required secret details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_create(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderSecretCreateRequestData data2: (required)
        :param ProviderSecretCreateRequestData data: (required)
        :return: ProviderSecretCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_create_with_http_info(data2, data, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_create_with_http_info(data2, data, **kwargs)  # noqa: E501
            return data

    def providers_secrets_create_with_http_info(self, data2, data, **kwargs):  # noqa: E501
        """Create a new secret  # noqa: E501

        Add a new secret to the system by providing the required secret details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_create_with_http_info(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderSecretCreateRequestData data2: (required)
        :param ProviderSecretCreateRequestData data: (required)
        :return: ProviderSecretCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `providers_secrets_create`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `providers_secrets_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderSecretCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_create(self, data2, data, **kwargs):  # noqa: E501
        """Create a new secret  # noqa: E501

        Add a new secret to the system by providing the required secret details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_create(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderSecretCreateRequestData data2: (required)
        :param ProviderSecretCreateRequestData data: (required)
        :return: ProviderSecretCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_create_with_http_info(data2, data, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_create_with_http_info(data2, data, **kwargs)  # noqa: E501
            return data

    def providers_secrets_create_with_http_info(self, data2, data, **kwargs):  # noqa: E501
        """Create a new secret  # noqa: E501

        Add a new secret to the system by providing the required secret details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_create_with_http_info(data2, data, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ProviderSecretCreateRequestData data2: (required)
        :param ProviderSecretCreateRequestData data: (required)
        :return: ProviderSecretCreateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `providers_secrets_create`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `providers_secrets_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderSecretCreateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_destroy(self, id, **kwargs):  # noqa: E501
        """Delete a secret  # noqa: E501

        Remove a secret from the system by their ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_destroy(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_destroy_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_destroy_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def providers_secrets_destroy_with_http_info(self, id, **kwargs):  # noqa: E501
        """Delete a secret  # noqa: E501

        Remove a secret from the system by their ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_destroy_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_destroy" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_secrets_destroy`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets/{id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_list(self, **kwargs):  # noqa: E501
        """List all secrets  # noqa: E501

        Retrieve a list of all secrets with options for filtering by various criteria.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] fields_provider_secrets: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param date filter_inserted_at:
        :param str filter_name:
        :param str filter_name__icontains:
        :param str filter_provider:
        :param str filter_search: A search term.
        :param date filter_updated_at:
        :param int page_number: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param list[str] sort: [list of fields to sort by](https://jsonapi.org/format/#fetching-sorting)
        :return: PaginatedProviderSecretList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def providers_secrets_list_with_http_info(self, **kwargs):  # noqa: E501
        """List all secrets  # noqa: E501

        Retrieve a list of all secrets with options for filtering by various criteria.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] fields_provider_secrets: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :param date filter_inserted_at:
        :param str filter_name:
        :param str filter_name__icontains:
        :param str filter_provider:
        :param str filter_search: A search term.
        :param date filter_updated_at:
        :param int page_number: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param list[str] sort: [list of fields to sort by](https://jsonapi.org/format/#fetching-sorting)
        :return: PaginatedProviderSecretList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fields_provider_secrets', 'filter_inserted_at', 'filter_name', 'filter_name__icontains', 'filter_provider', 'filter_search', 'filter_updated_at', 'page_number', 'page_size', 'sort']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'fields_provider_secrets' in params:
            query_params.append(('fields[provider-secrets]', params['fields_provider_secrets']))  # noqa: E501
            collection_formats['fields[provider-secrets]'] = 'csv'  # noqa: E501
        if 'filter_inserted_at' in params:
            query_params.append(('filter[inserted_at]', params['filter_inserted_at']))  # noqa: E501
        if 'filter_name' in params:
            query_params.append(('filter[name]', params['filter_name']))  # noqa: E501
        if 'filter_name__icontains' in params:
            query_params.append(('filter[name__icontains]', params['filter_name__icontains']))  # noqa: E501
        if 'filter_provider' in params:
            query_params.append(('filter[provider]', params['filter_provider']))  # noqa: E501
        if 'filter_search' in params:
            query_params.append(('filter[search]', params['filter_search']))  # noqa: E501
        if 'filter_updated_at' in params:
            query_params.append(('filter[updated_at]', params['filter_updated_at']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('page[number]', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page[size]', params['page_size']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501
            collection_formats['sort'] = 'csv'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedProviderSecretList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_partial_update(self, body, id, **kwargs):  # noqa: E501
        """Partially update a secret  # noqa: E501

        Update certain fields of an existing secret's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_partial_update(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderSecretUpdateRequest body: (required)
        :param str id: (required)
        :return: ProviderSecretUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_partial_update_with_http_info(body, id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_partial_update_with_http_info(body, id, **kwargs)  # noqa: E501
            return data

    def providers_secrets_partial_update_with_http_info(self, body, id, **kwargs):  # noqa: E501
        """Partially update a secret  # noqa: E501

        Update certain fields of an existing secret's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_partial_update_with_http_info(body, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderSecretUpdateRequest body: (required)
        :param str id: (required)
        :return: ProviderSecretUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `providers_secrets_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_secrets_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderSecretUpdateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_partial_update(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update a secret  # noqa: E501

        Update certain fields of an existing secret's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_partial_update(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderSecretUpdateRequestData data2: (required)
        :param PatchedProviderSecretUpdateRequestData data: (required)
        :param str id: (required)
        :return: ProviderSecretUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
            return data

    def providers_secrets_partial_update_with_http_info(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update a secret  # noqa: E501

        Update certain fields of an existing secret's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_partial_update_with_http_info(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderSecretUpdateRequestData data2: (required)
        :param PatchedProviderSecretUpdateRequestData data: (required)
        :param str id: (required)
        :return: ProviderSecretUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `providers_secrets_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `providers_secrets_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_secrets_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderSecretUpdateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_partial_update(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update a secret  # noqa: E501

        Update certain fields of an existing secret's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_partial_update(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderSecretUpdateRequestData data2: (required)
        :param PatchedProviderSecretUpdateRequestData data: (required)
        :param str id: (required)
        :return: ProviderSecretUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_partial_update_with_http_info(data2, data, id, **kwargs)  # noqa: E501
            return data

    def providers_secrets_partial_update_with_http_info(self, data2, data, id, **kwargs):  # noqa: E501
        """Partially update a secret  # noqa: E501

        Update certain fields of an existing secret's information without affecting other fields.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_partial_update_with_http_info(data2, data, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PatchedProviderSecretUpdateRequestData data2: (required)
        :param PatchedProviderSecretUpdateRequestData data: (required)
        :param str id: (required)
        :return: ProviderSecretUpdateResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data2', 'data', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data2' is set
        if ('data2' not in params or
                params['data2'] is None):
            raise ValueError("Missing the required parameter `data2` when calling `providers_secrets_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `providers_secrets_partial_update`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_secrets_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501
        if 'data' in params:
            form_params.append(('data', params['data']))  # noqa: E501

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/vnd.api+json', 'application/x-www-form-urlencoded', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets/{id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderSecretUpdateResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def providers_secrets_retrieve(self, id, **kwargs):  # noqa: E501
        """Retrieve data from a secret  # noqa: E501

        Fetch detailed information about a specific secret by their ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_retrieve(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param list[str] fields_provider_secrets: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :return: ProviderSecretResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.providers_secrets_retrieve_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.providers_secrets_retrieve_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def providers_secrets_retrieve_with_http_info(self, id, **kwargs):  # noqa: E501
        """Retrieve data from a secret  # noqa: E501

        Fetch detailed information about a specific secret by their ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.providers_secrets_retrieve_with_http_info(id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str id: (required)
        :param list[str] fields_provider_secrets: endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.
        :return: ProviderSecretResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'fields_provider_secrets']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method providers_secrets_retrieve" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `providers_secrets_retrieve`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'fields_provider_secrets' in params:
            query_params.append(('fields[provider-secrets]', params['fields_provider_secrets']))  # noqa: E501
            collection_formats['fields[provider-secrets]'] = 'csv'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.api+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['jwtAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/providers/secrets/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ProviderSecretResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
